all_teachers_test_data = {
    "teachers": [
        {"id": 1, "name": "Jan", "last_name": "Kowalski", "email": "jan.k@example.com"},
        {"id": 3, "name": "string", "last_name": "string", "email": "user@example.com"},
        {"id": 9, "name": "Jan", "last_name": "Nowak", "email": "jn@example.com"},
        {"id": 12, "name": "Steve", "last_name": "Newman", "email": "sn@example.com"},
        {"id": 11, "name": "Jan", "last_name": "Kazimierz", "email": "jk@example.com"},
    ]
}

all_exercises_test_data = {
    "exercises": [
        {
            "id": 1,
            "name": "prawo pracy",
            "study_year": 3,
            "semester": 2,
            "hours_exercises": 30,
            "groups_exercises": 4,
            "teacher_id": 1,
            "sum_exercises_hours": 120,
        },
        {
            "id": 2,
            "name": "prawo pracy2",
            "study_year": 4,
            "semester": 1,
            "hours_exercises": 30,
            "groups_exercises": 4,
            "teacher_id": 9,
            "sum_exercises_hours": 120,
        },
    ]
}

all_lectures_test_data = {
    "lectures": [
        {
            "id": 1,
            "name": "prawo pracy",
            "study_year": 3,
            "semester": 2,
            "hours_lectures": 60,
            "groups_lectures": 1,
            "teacher_id": 1,
            "sum_lectures_hours": 60,
        },
        {
            "id": 3,
            "name": "prawo rzymskie",
            "study_year": 1,
            "semester": 1,
            "hours_lectures": 60,
            "groups_lectures": 1,
            "teacher_id": 1,
            "sum_lectures_hours": 60,
        },
        {
            "id": 2,
            "name": "prawo pracy2",
            "study_year": 4,
            "semester": 1,
            "hours_lectures": 60,
            "groups_lectures": 1,
            "teacher_id": 3,
            "sum_lectures_hours": 60,
        },
    ]
}

[
    {
        "id_x": 16,
        "name_x": "Ekonomia",
        "study_year": 4,
        "semester": 2,
        "hours_lectures": 60.0,
        "groups_lectures": 1.0,
        "teacher_id": 6,
        "sum_lectures_hours": 60.0,
        "hours_exercises": nan,
        "groups_exercises": nan,
        "sum_exercises_hours": nan,
        "id_y": 6,
        "name_y": "Cyryl",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 6,
        "name_x": "Ekonomia",
        "study_year": 4,
        "semester": 1,
        "hours_lectures": nan,
        "groups_lectures": nan,
        "teacher_id": 6,
        "sum_lectures_hours": nan,
        "hours_exercises": 50.0,
        "groups_exercises": 3.0,
        "sum_exercises_hours": 150.0,
        "id_y": 6,
        "name_y": "Cyryl",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 7,
        "name_x": "Historiae",
        "study_year": 1,
        "semester": 1,
        "hours_lectures": nan,
        "groups_lectures": nan,
        "teacher_id": 7,
        "sum_lectures_hours": nan,
        "hours_exercises": 30.0,
        "groups_exercises": 3.0,
        "sum_exercises_hours": 90.0,
        "id_y": 7,
        "name_y": "Roman",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 19,
        "name_x": "Prawo cywilne",
        "study_year": 4,
        "semester": 1,
        "hours_lectures": 60.0,
        "groups_lectures": 1.0,
        "teacher_id": 9,
        "sum_lectures_hours": 60.0,
        "hours_exercises": nan,
        "groups_exercises": nan,
        "sum_exercises_hours": nan,
        "id_y": 9,
        "name_y": "Czeslaw",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 17,
        "name_x": "Prawo pracy",
        "study_year": 3,
        "semester": 2,
        "hours_lectures": 60.0,
        "groups_lectures": 1.0,
        "teacher_id": 7,
        "sum_lectures_hours": 60.0,
        "hours_exercises": nan,
        "groups_exercises": nan,
        "sum_exercises_hours": nan,
        "id_y": 7,
        "name_y": "Roman",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 18,
        "name_x": "Prawo pracy 2",
        "study_year": 4,
        "semester": 1,
        "hours_lectures": 60.0,
        "groups_lectures": 1.0,
        "teacher_id": 8,
        "sum_lectures_hours": 60.0,
        "hours_exercises": nan,
        "groups_exercises": nan,
        "sum_exercises_hours": nan,
        "id_y": 8,
        "name_y": "Szczepan",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 11,
        "name_x": "Prawo1",
        "study_year": 1,
        "semester": 1,
        "hours_lectures": 30.0,
        "groups_lectures": 15.0,
        "teacher_id": 19,
        "sum_lectures_hours": 450.0,
        "hours_exercises": nan,
        "groups_exercises": nan,
        "sum_exercises_hours": nan,
        "id_y": 19,
        "name_y": "Piotr",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 1,
        "name_x": "Prawo1",
        "study_year": 1,
        "semester": 1,
        "hours_lectures": nan,
        "groups_lectures": nan,
        "teacher_id": 12,
        "sum_lectures_hours": nan,
        "hours_exercises": 90.0,
        "groups_exercises": 1.0,
        "sum_exercises_hours": 90.0,
        "id_y": 12,
        "name_y": "Feliks",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 12,
        "name_x": "Prawo2",
        "study_year": 1,
        "semester": 2,
        "hours_lectures": 30.0,
        "groups_lectures": 15.0,
        "teacher_id": 18,
        "sum_lectures_hours": 450.0,
        "hours_exercises": nan,
        "groups_exercises": nan,
        "sum_exercises_hours": nan,
        "id_y": 18,
        "name_y": "Ludwik",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 2,
        "name_x": "Prawo2",
        "study_year": 1,
        "semester": 2,
        "hours_lectures": nan,
        "groups_lectures": nan,
        "teacher_id": 14,
        "sum_lectures_hours": nan,
        "hours_exercises": 30.0,
        "groups_exercises": 3.0,
        "sum_exercises_hours": 90.0,
        "id_y": 14,
        "name_y": "Henryk",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 13,
        "name_x": "Prawo3",
        "study_year": 2,
        "semester": 1,
        "hours_lectures": 30.0,
        "groups_lectures": 15.0,
        "teacher_id": 17,
        "sum_lectures_hours": 450.0,
        "hours_exercises": nan,
        "groups_exercises": nan,
        "sum_exercises_hours": nan,
        "id_y": 17,
        "name_y": "Klemens",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 3,
        "name_x": "Prawo3",
        "study_year": 2,
        "semester": 1,
        "hours_lectures": nan,
        "groups_lectures": nan,
        "teacher_id": 15,
        "sum_lectures_hours": nan,
        "hours_exercises": 30.0,
        "groups_exercises": 4.0,
        "sum_exercises_hours": 120.0,
        "id_y": 15,
        "name_y": "Henryk",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 4,
        "name_x": "Prawo3",
        "study_year": 2,
        "semester": 1,
        "hours_lectures": nan,
        "groups_lectures": nan,
        "teacher_id": 6,
        "sum_lectures_hours": nan,
        "hours_exercises": 30.0,
        "groups_exercises": 3.0,
        "sum_exercises_hours": 90.0,
        "id_y": 6,
        "name_y": "Cyryl",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 14,
        "name_x": "Prawo4",
        "study_year": 2,
        "semester": 2,
        "hours_lectures": 30.0,
        "groups_lectures": 1.0,
        "teacher_id": 6,
        "sum_lectures_hours": 30.0,
        "hours_exercises": nan,
        "groups_exercises": nan,
        "sum_exercises_hours": nan,
        "id_y": 6,
        "name_y": "Cyryl",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 15,
        "name_x": "Prawo5",
        "study_year": 3,
        "semester": 1,
        "hours_lectures": 45.0,
        "groups_lectures": 1.0,
        "teacher_id": 6,
        "sum_lectures_hours": 45.0,
        "hours_exercises": nan,
        "groups_exercises": nan,
        "sum_exercises_hours": nan,
        "id_y": 6,
        "name_y": "Cyryl",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
    {
        "id_x": 5,
        "name_x": "Prawo5",
        "study_year": 3,
        "semester": 2,
        "hours_lectures": nan,
        "groups_lectures": nan,
        "teacher_id": 6,
        "sum_lectures_hours": nan,
        "hours_exercises": 30.0,
        "groups_exercises": 4.0,
        "sum_exercises_hours": 120.0,
        "id_y": 6,
        "name_y": "Cyryl",
        "last_name": "Wykladowca",
        "email": "kkw@example.com",
    },
]


class SummaryClassesDepartmentReport(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    subject: str
    faculty: str
    study_year: int
    semester: int
    hours_lectures: int
    hours_exercises: int
    groups: int
    teachers: {
        lecture_teacher: str,
        exercise_teachers: int,
        groups_for_teacher: int,
        hours_for_teacher: int,
    }
