version: '3.9'
name: faculty-hours-raport
services:
  web:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ../:/app/
    ports:
      - "8200:8200"
    networks:
      - faculty_network
      - common_network
networks:
  faculty_network:
    driver: bridge
  common_network:
    external: true
