version: '3.9'
name: faculty-hours-raport
services:
  report:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ../:/app/
    ports:
      - "8200:8200"
    networks:
      - faculty_network
      - report_network
      - common_network
  mongos:
    container_name: mongos-report
    image: mongo
    ports:
      - "30000:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo:/data/db
    networks:
      - report_network
networks:
  faculty_network:
    driver: bridge
  report_network:
    driver: bridge
  common_network:
    external: true
volumes:
  mongo:
